name: Go1.18
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18.6
      uses: actions/setup-go@v1
      with:
        go-version: 1.18.6
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -p=1 ./...
